AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Security Monitoring Dashboard

Globals:
  Function:
    Timeout: 30
    Runtime: python3.13
    Environment:
      Variables:
        EVENTS_TABLE: !Ref EventsTable
        ALERTS_TABLE: !Ref AlertsTable
        SNS_TOPIC_ARN: !Ref SecurityAlertsTopic

Resources:
  # DynamoDB Tables
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SecurityEvents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: sourceIp
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: SourceIpIndex
          KeySchema:
            - AttributeName: sourceIp
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  AlertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SecurityAlerts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: alertId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: severity
          AttributeType: S
      KeySchema:
        - AttributeName: alertId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: SeverityIndex
          KeySchema:
            - AttributeName: severity
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # SNS Topic for Alerts
  SecurityAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SecurityAlerts
      DisplayName: Security Monitoring Alerts

  # Lambda Functions
  LogIngestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SecurityLogIngestion
      CodeUri: src/ingestion/
      Handler: handler.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /ingest
            Method: POST
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Description: Simulated log ingestion

  ThreatDetectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ThreatDetection
      CodeUri: src/detection/
      Handler: handler.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AlertsTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SecurityAlertsTopic.TopicName
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt EventsTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 5

  AlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AlertNotification
      CodeUri: src/alerts/
      Handler: handler.lambda_handler
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SecurityAlertsTopic.TopicName
        - DynamoDBCrudPolicy:
            TableName: !Ref AlertsTable

  DashboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DashboardAPI
      CodeUri: src/dashboard/
      Handler: handler.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventsTable
        - DynamoDBReadPolicy:
            TableName: !Ref AlertsTable
      Events:
        GetEvents:
          Type: Api
          Properties:
            Path: /events
            Method: GET
        GetAlerts:
          Type: Api
          Properties:
            Path: /alerts
            Method: GET
        GetStats:
          Type: Api
          Properties:
            Path: /stats
            Method: GET

  # CloudWatch Alarms
  HighSeverityAlertsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: HighSeveritySecurityAlerts
      AlarmDescription: Alert when critical security events are detected
      MetricName: CriticalAlerts
      Namespace: SecurityMonitoring
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SecurityAlertsTopic

  # S3 Bucket for Dashboard
  DashboardBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-dashboard-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  DashboardBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DashboardBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${DashboardBucket.Arn}/*'

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  DashboardURL:
    Description: Dashboard S3 Website URL
    Value: !GetAtt DashboardBucket.WebsiteURL
  SNSTopicArn:
    Description: SNS Topic ARN for alerts
    Value: !Ref SecurityAlertsTopic
  EventsTableName:
    Description: DynamoDB Events Table
    Value: !Ref EventsTable
  AlertsTableName:
    Description: DynamoDB Alerts Table
    Value: !Ref AlertsTable
